export const sample_foods:any[] = [
    {
        id: '1',
        name: 'Pizza Pepperoni',
        price: 10,
        cookTime: '10-20',
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'assets/pizzapeproni.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '2',
        name: 'Meatball',
        price: 20,
        cookTime: '20-30',
        favorite: true,
        origins: ['persia', 'middle east', 'china'],
        stars: 4.7,
        imageUrl:'./assets/meatballs.jpg',
        tags: ['SlowFood', 'Lunch'],
    },
    {
        id: '3',
        name: 'Hamburger',
        price: 5,
        cookTime: '10-20',
        favorite: false,
        origins: ['germany', 'us'],
        stars: 3.7,
        imageUrl:'./assets/hamburger.jpg',
        tags: ['FastFood', 'Hamburger'],
    },
    {
        id: '4',
        name: 'Fried Potatoes',
        price: 2,
        cookTime: '10-20',
        favorite: true,
        origins: ['france', 'belgium'],
        stars: 3.5,
        imageUrl:'./assets/friedpotatoes.jpg',
        tags: ['FastFood', 'Fry'],
    },
    {
        id: '5',
        name: 'Chicken Soup',
        price: 11,
        cookTime: '40-50',
        favorite: true,
        origins: ['indian', 'asia'],
        stars: 4.5,
        imageUrl:'./assets/chickensoup.jpg',
        tags: ['SlowFood', 'Lunch'],
    },
    {
        id: '6',
        name: 'Vegitable Pizza',
        price: 9,
        cookTime: '40-50',
        favorite: false,
        origins: ['italy'],
        stars: 3.5,
        imageUrl:'./assets/vegitablepizza.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '7',
        name: 'Cheese Burger',
        price: 12,
        cookTime: '30-40',
        favorite: false,
        origins: ['American'],
        stars: 4.7,
        imageUrl:'./assets/cheesburger.jpg',
        tags: ['FastFood', 'HamBurger', 'Burger'],
    },
    {
        id: '8',
        name: 'chicken roast',
        price: 9,
        cookTime: '40-50',
        favorite: true,
        origins: ['italy'],
        stars: 5.0,
        imageUrl:'./assets/chickenroast.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '9',
        name: 'Noodels',
        price: 8,
        cookTime: '40-50',
        favorite: false,
        origins: ['italy'],
        stars: 3.0,
        imageUrl:'./assets/noodles.jpg',
        tags: ['FastFood'],
    },
    {
        id: '10',
        name: 'Chicken Thupka',
        price: 9,
        cookTime: '40-50',
        favorite: true,
        origins: ['italy', 'indian'],
        stars: 4.5,
        imageUrl:'./assets/thupka.jpg',
        tags: ['SlowFood', 'Lunch'],
    },
]
export const sample_tags:any[] = [
    { name: 'All', count: 6 },
    { name: 'FastFood', count: 4 },
    { name: 'Pizza', count: 2 },
    { name: 'Lunch', count: 3 },
    { name: 'SlowFood', count: 2 },
    { name: 'Hamburger', count: 1 },
    { name: 'Fry', count: 1 },
    { name: 'Soup', count: 1 },
  ]
  export const sample_users: any[] = [
    {
      name: "John Doe",
      email: "john@gmail.com",
      password: "12345",
      address: "Toronto On",
      isAdmin: true,
    },
    {
      name: "Jane Doe",
      email: "jane@gmail.com",
      password: "12345",
      address: "Shanghai",
      isAdmin: false,
    },
  ];